<?php

class OldUsersSeeder extends Seeder {

	public function run()
	{
		DB::disableQueryLog();

		$users = array(
			array(
				'nickname' => '',
				'name' => 'Trevor Mesnik',
				'email' => 'trevor.mesnik@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1985-06-05',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388168295),
				'updated_at' => date('Y-m-d H:i:s', 1388168295),
				'available' => 1,
				'bio' => 'I am business owner and have started and managed more then 10 successful companies.',
				'price' => '40.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Amandajones605',
				'name' => 'Amanda',
				'email' => 'amandajones605@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1986-02-09',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388169413),
				'updated_at' => date('Y-m-d H:i:s', 1388169413),
				'available' => 1,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Chris Salisbury',
				'email' => 'chrissalisbury90@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1978-10-18',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388186424),
				'updated_at' => date('Y-m-d H:i:s', 1388186424),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Chris Paul Salisbury',
				'email' => 'chrisburberry@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1978-10-18',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388186946),
				'updated_at' => date('Y-m-d H:i:s', 1388186946),
				'available' => 1,
				'bio' => 'Marketing at its finest.',
				'price' => '45.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'PAblo',
				'name' => 'Pablo Polidoro',
				'email' => 'pabloapolidoro@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1987-02-24',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388191774),
				'updated_at' => date('Y-m-d H:i:s', 1388191774),
				'available' => 1,
				'bio' => 'Licensed California Paramedic, Graduated from Southwestern College Paramedic Class 34. Currently a full time Paramedic in San Diego County. 5+ years of EMS experience.',
				'price' => '24.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Stryker',
				'name' => 'mike',
				'email' => 'mikesyden@hotmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1985-09-19',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388199497),
				'updated_at' => date('Y-m-d H:i:s', 1388199497),
				'available' => 1,
				'bio' => 'test',
				'price' => '78.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Scud',
				'name' => 'Andrew Scudder',
				'email' => '1andrewscudder@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1989-12-15',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388204898),
				'updated_at' => date('Y-m-d H:i:s', 1388204898),
				'available' => 1,
				'bio' => 'Hi Everyone! 
			My name is Andrew Scudder. 

			I would love to teach you anything relating to Photography, Business Start up and Marketing. 

			Im Fun, Friendly and ready to help!

			Hope to hear from you soon!',
				'price' => '0.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'sanepara',
				'name' => 'Ravi Sanepara',
				'email' => 'rsanepara@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1990-07-18',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388221931),
				'updated_at' => date('Y-m-d H:i:s', 1388221931),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'SRG',
				'name' => 'Sudhi Ranjan Ganguly',
				'email' => 'langstudycentre@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1969-06-26',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388222217),
				'updated_at' => date('Y-m-d H:i:s', 1388222217),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Alex Sorin Dachin',
				'email' => 'alex_tm2010@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1995-08-20',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388243879),
				'updated_at' => date('Y-m-d H:i:s', 1388243879),
				'available' => 1,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Ty Jones',
				'email' => 'tjcollege2012@live.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1993-08-30',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388246603),
				'updated_at' => date('Y-m-d H:i:s', 1388246603),
				'available' => 1,
				'bio' => 'I can teach anything from fractions and decimals upto Pythagorean theorem and solving proofs',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'roshu',
				'name' => 'Alexandru Andrei Lamba',
				'email' => 'roshkattu94@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1993-02-12',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388247758),
				'updated_at' => date('Y-m-d H:i:s', 1388247758),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Drew',
				'name' => 'Andrew Jones',
				'email' => 'drew258531@aol.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1985-01-25',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388348887),
				'updated_at' => date('Y-m-d H:i:s', 1388348887),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Whitnie',
				'name' => 'Whitnie selby',
				'email' => 'Whitstout@hotmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1986-06-25',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388420421),
				'updated_at' => date('Y-m-d H:i:s', 1388420421),
				'available' => 1,
				'bio' => 'I have been a Sonographer for 5 1/2 years and love my job. I am constantly learning ways to better my skills and a better understanding of how the body works. I currently work in a hospital and outpatient setting.  I would love to be apart of your learning adventure! I can help with scanning techniques and answer any and all questions regarding general ultrasound.',
				'price' => '30.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Griff',
				'name' => 'DRGriffith',
				'email' => 'griffcomm40@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1968-02-06',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388462540),
				'updated_at' => date('Y-m-d H:i:s', 1388462540),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Sary',
				'name' => 'Sarahy',
				'email' => 'sarahyt@ymail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1980-01-01',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388466632),
				'updated_at' => date('Y-m-d H:i:s', 1388466632),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'sheiladz',
				'name' => 'sheila vinson',
				'email' => 'sheila.vinson@wilburtondiggers.org',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1967-03-26',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388546261),
				'updated_at' => date('Y-m-d H:i:s', 1388546261),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Sierra',
				'name' => 'Sierra Martin',
				'email' => 'sierra.martin2013@outlook.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1995-03-04',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388548019),
				'updated_at' => date('Y-m-d H:i:s', 1388548019),
				'available' => 1,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'LAw',
				'name' => 'LAW JIA XIAN',
				'email' => 'christopherguanxianlaw@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1995-08-11',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388550199),
				'updated_at' => date('Y-m-d H:i:s', 1388550199),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'matthew mesnik',
				'email' => 'matt@mesnikweb.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1977-11-24',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388553273),
				'updated_at' => date('Y-m-d H:i:s', 1388553273),
				'available' => 1,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'gwen mclellan',
				'email' => 'gwenmclellan@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1972-01-08',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388555212),
				'updated_at' => date('Y-m-d H:i:s', 1388555212),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'gwen mclellan',
				'email' => 'gwen.mclellan@appling.k12.ga.us',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1972-01-08',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388555554),
				'updated_at' => date('Y-m-d H:i:s', 1388555554),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Landon Mesnik',
				'email' => 'trevor@studysquare.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1991-06-09',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388562502),
				'updated_at' => date('Y-m-d H:i:s', 1388562502),
				'available' => 1,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'dizzyraybabe',
				'name' => 'desiree',
				'email' => 'desireemacarthur@Hotmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1996-11-14',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388623311),
				'updated_at' => date('Y-m-d H:i:s', 1388623311),
				'available' => 1,
				'bio' => 'Just a Scottish girl looking to share who knowledge of Gàidhlig in hopes of earning money to attend a Scottish secondary school.',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Jennifer',
				'name' => 'Jennifer Greeley',
				'email' => 'jennifergreeley8@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1974-05-18',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388633455),
				'updated_at' => date('Y-m-d H:i:s', 1388633455),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'kgooch',
				'name' => 'Katie Gooch',
				'email' => 'katgooch1212@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1980-08-30',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388635984),
				'updated_at' => date('Y-m-d H:i:s', 1388635984),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Pam',
				'name' => 'Pamela Kendall',
				'email' => 'pameladkendall@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1966-11-22',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388636463),
				'updated_at' => date('Y-m-d H:i:s', 1388636463),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Alex',
				'name' => 'Alexander Tumms Collins',
				'email' => 'wizzybutton1@aol.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1975-09-15',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388638121),
				'updated_at' => date('Y-m-d H:i:s', 1388638121),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Donita Green',
				'email' => 'greendonita86@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1986-10-24',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388639240),
				'updated_at' => date('Y-m-d H:i:s', 1388639240),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Rachel',
				'name' => 'Rachel Crist',
				'email' => 'rachel.n.crist@vanderbilt.edu',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1992-06-15',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388640059),
				'updated_at' => date('Y-m-d H:i:s', 1388640059),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Katie76',
				'name' => 'Katrina Looney',
				'email' => 'katameeli@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1976-12-29',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388702864),
				'updated_at' => date('Y-m-d H:i:s', 1388702864),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Anna Kelly',
				'email' => 'ankanelly96@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1996-12-04',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1388728360),
				'updated_at' => date('Y-m-d H:i:s', 1388728360),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Annu',
				'name' => 'Anand',
				'email' => 'anandtiwariseo@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1988-11-10',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388779965),
				'updated_at' => date('Y-m-d H:i:s', 1388779965),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Collin Scudder',
				'email' => 'Collinscudder@aim.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1992-01-15',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1388863099),
				'updated_at' => date('Y-m-d H:i:s', 1388863099),
				'available' => 1,
				'bio' => '',
				'price' => '25.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Snow',
				'name' => 'Snow Ross',
				'email' => 'sross@mdirss.org',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1972-07-10',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389046996),
				'updated_at' => date('Y-m-d H:i:s', 1389046996),
				'available' => 1,
				'bio' => 'I have a Masters Degree in education. I have been teaching for the last 18 years. I am available to help you with any academic needs.',
				'price' => '30.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Patricia',
				'name' => 'Patricia',
				'email' => 'patricia.ukena@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1993-09-09',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389073499),
				'updated_at' => date('Y-m-d H:i:s', 1389073499),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'maria',
				'name' => 'MARIA IMAD',
				'email' => 'maria.imad24@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1985-08-08',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389117615),
				'updated_at' => date('Y-m-d H:i:s', 1389117615),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Sandrac0483',
				'name' => 'Cassandra Nix',
				'email' => 'sandra0483@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1983-04-01',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389124842),
				'updated_at' => date('Y-m-d H:i:s', 1389124842),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Lulugal',
				'name' => 'Laurie A. Groth-Walters',
				'email' => 'lulugal22459@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1959-02-24',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389125519),
				'updated_at' => date('Y-m-d H:i:s', 1389125519),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Patrick',
				'name' => 'allaglo',
				'email' => 'patrick.allaglo@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1994-06-04',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1389129663),
				'updated_at' => date('Y-m-d H:i:s', 1389129663),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Danielle',
				'name' => 'Danielle Menzari',
				'email' => 'dannid@twcny.rr.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1982-09-13',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389138895),
				'updated_at' => date('Y-m-d H:i:s', 1389138895),
				'available' => 1,
				'bio' => 'I have a Bachelor\'s Degree in Business Accounting and currently work as an Accounts Payable Clerk for a Not-For-Profit company that rejuvenates neighborhoods.  Managing over 20 properties included, but not limited to, entering and paying all invoices, keeping track of all taxes and paying them on a timely basis, monthly reconciliations, and allocations.  I am extremely efficient with multiple different computer programs and use accounting procedures on a daily basis.  I am also proficient in writing and spelling.  I am here to help you get through school and hope to learn something myself.  Please contact me if you have any questions.',
				'price' => '40.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Derek Bergstrom',
				'email' => 'derek_bergstrom@hotmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1984-09-12',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1389142108),
				'updated_at' => date('Y-m-d H:i:s', 1389142108),
				'available' => 0,
				'bio' => '',
				'price' => '40.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Kesha',
				'name' => 'NaKesha Strunk',
				'email' => 'babeeboo6783167@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1981-12-14',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389144848),
				'updated_at' => date('Y-m-d H:i:s', 1389144848),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Callie',
				'name' => 'Callie Silva',
				'email' => 'calliesilva@aol.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1997-02-26',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389144979),
				'updated_at' => date('Y-m-d H:i:s', 1389144979),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'court',
				'name' => 'Courtney',
				'email' => 'courtneykaiser1@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1991-10-12',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389145444),
				'updated_at' => date('Y-m-d H:i:s', 1389145444),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'kdsmith',
				'name' => 'kayla smith',
				'email' => 'kdsmith093013@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1992-01-17',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389145754),
				'updated_at' => date('Y-m-d H:i:s', 1389145754),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'joy',
				'name' => 'Joy Guthrie',
				'email' => 'nana-joy@msn.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1960-01-13',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389145883),
				'updated_at' => date('Y-m-d H:i:s', 1389145883),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Jenn',
				'name' => 'Jennifer Sheppard',
				'email' => 'mrstink42006@aol.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1978-09-29',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389146387),
				'updated_at' => date('Y-m-d H:i:s', 1389146387),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Mr. Jarvis',
				'name' => 'DeJarvis Floyd',
				'email' => 'dejarvisfloyd@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1980-02-05',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1389146649),
				'updated_at' => date('Y-m-d H:i:s', 1389146649),
				'available' => 1,
				'bio' => 'I enjoy helping students learn and improve there GPA.  I have a Master\'s Degree in Business Education from MTSU.  I am ready to help you!',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'JeanF',
				'name' => 'Jean Friedman',
				'email' => 'jean_friedman@hotmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1965-01-25',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389148424),
				'updated_at' => date('Y-m-d H:i:s', 1389148424),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'zakia',
				'name' => 'Zakia Imran',
				'email' => 'zakiasharique@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1984-10-07',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389164262),
				'updated_at' => date('Y-m-d H:i:s', 1389164262),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Rehab Hafeez Siddiqui',
				'email' => 'rehab_siddiqui@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1988-12-27',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389168503),
				'updated_at' => date('Y-m-d H:i:s', 1389168503),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Chris',
				'name' => 'Christopher Lee Gross',
				'email' => 'christopher.l.gross@vanderbilt.edu',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1991-01-21',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1389219736),
				'updated_at' => date('Y-m-d H:i:s', 1389219736),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'OMy OMa',
				'name' => 'Rhonda Ashburn',
				'email' => 'r2ashburn@att.net',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1954-08-31',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389269426),
				'updated_at' => date('Y-m-d H:i:s', 1389269426),
				'available' => 0,
				'bio' => '',
				'price' => '30.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Johnson',
				'name' => 'Caleb',
				'email' => 'caleb.johnson@topper.wku.edu',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1987-07-28',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1389287732),
				'updated_at' => date('Y-m-d H:i:s', 1389287732),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Erica',
				'email' => 'jlo7ga@aol.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1992-09-06',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389318626),
				'updated_at' => date('Y-m-d H:i:s', 1389318626),
				'available' => 1,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Fakey',
				'name' => 'Mr/Mrs Fake',
				'email' => 'mikesyden@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '2000-04-04',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389407000),
				'updated_at' => date('Y-m-d H:i:s', 1389407000),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Ebony',
				'name' => 'Ebony Howard',
				'email' => 'tutoringforsuccess@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1987-05-28',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389414828),
				'updated_at' => date('Y-m-d H:i:s', 1389414828),
				'available' => 1,
				'bio' => 'I am motivated to help you succeed in your studies. I can guarantee that I will help you improve your grade if you are willing to give me the time to give you a better understanding of the course you are taking. The subjects I am tutoring in, I have made an A and look forward to assisting you an getting an A as well.',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Ruqayyah',
				'name' => 'Ruqayyah',
				'email' => 'ruqayyaharchie@aol.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1981-01-20',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389546194),
				'updated_at' => date('Y-m-d H:i:s', 1389546194),
				'available' => 1,
				'bio' => 'I am currently a full time Business/Accounting Professor, with 5 years of experience as a professor. I am also a contract tutor for various universities. I have a flexible schedule and I would love to help you successfully master accounting and business concepts.',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'ayesha',
				'name' => 'ayesha',
				'email' => 'mmmmmmm@hotmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1985-01-01',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389767724),
				'updated_at' => date('Y-m-d H:i:s', 1389767724),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'zubi abi',
				'name' => 'Zubaida Ahmed',
				'email' => 'galaxy1080@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1958-06-27',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1389781009),
				'updated_at' => date('Y-m-d H:i:s', 1389781009),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'me war',
				'email' => 'mewar@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '2002-02-04',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1390257351),
				'updated_at' => date('Y-m-d H:i:s', 1390257351),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Nermin Nabeh Al-Rousan',
				'email' => 'nermin_alrousan@hotmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1984-05-25',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1390309248),
				'updated_at' => date('Y-m-d H:i:s', 1390309248),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Tiff',
				'name' => 'Tiffany',
				'email' => 'Tiffanyreynolds02@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1983-11-02',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1390312396),
				'updated_at' => date('Y-m-d H:i:s', 1390312396),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'epheterson',
				'name' => 'Eric L. Pheterson',
				'email' => 'Eric@buygood.us',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1988-07-17',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1390444252),
				'updated_at' => date('Y-m-d H:i:s', 1390444252),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'H',
				'name' => 'Haitch I. B.',
				'email' => 'haitch.i.b@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1985-01-01',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1390467501),
				'updated_at' => date('Y-m-d H:i:s', 1390467501),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'TianaStar',
				'name' => 'Tiana',
				'email' => 'fireflymediaservices@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1981-12-14',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1391319667),
				'updated_at' => date('Y-m-d H:i:s', 1391319667),
				'available' => 0,
				'bio' => '',
				'price' => '65.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Jakub Plešinger',
				'email' => 'jakubplesinger@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1985-04-28',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1391577401),
				'updated_at' => date('Y-m-d H:i:s', 1391577401),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Al',
				'name' => 'Alan',
				'email' => 'alan.levy@me.fom',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1992-03-10',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1392176377),
				'updated_at' => date('Y-m-d H:i:s', 1392176377),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Cristi Man',
				'email' => 'cristi_16_97@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1997-06-16',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1392247985),
				'updated_at' => date('Y-m-d H:i:s', 1392247985),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Scud',
				'name' => 'Scuder Butter',
				'email' => 'andrew@thinkFraminteractive.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1976-09-11',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1392522602),
				'updated_at' => date('Y-m-d H:i:s', 1392522602),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'matt',
				'name' => 'matt',
				'email' => 'matt@studybuddytoday.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1988-06-09',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1392673366),
				'updated_at' => date('Y-m-d H:i:s', 1392673366),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'D',
				'name' => 'Dhaval Patel',
				'email' => 'dhaval@dogoodseo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1983-09-16',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1393095350),
				'updated_at' => date('Y-m-d H:i:s', 1393095350),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'SummersLiu',
				'name' => 'Summer',
				'email' => 'liux3@lopers.unk.edu',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1990-11-24',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1394322970),
				'updated_at' => date('Y-m-d H:i:s', 1394322970),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Jamey',
				'name' => 'Jmks',
				'email' => 'u_wish_u_had_him@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1994-06-23',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1395017562),
				'updated_at' => date('Y-m-d H:i:s', 1395017562),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'lmotel',
				'name' => 'Lisa Motel',
				'email' => 'l_motel@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1964-11-11',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1396886903),
				'updated_at' => date('Y-m-d H:i:s', 1396886903),
				'available' => 1,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Monica Chavez',
				'email' => 'star_universemr@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1988-05-20',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1398743460),
				'updated_at' => date('Y-m-d H:i:s', 1398743460),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Neema',
				'email' => 'nshafigh@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1987-06-07',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1398928246),
				'updated_at' => date('Y-m-d H:i:s', 1398928246),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Mamadou',
				'email' => 'mamadou.sall@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1983-04-15',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1398928302),
				'updated_at' => date('Y-m-d H:i:s', 1398928302),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Reza',
				'name' => 'rezacal2000@yahoo.com',
				'email' => 'rezacal2000@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1994-02-08',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1398966043),
				'updated_at' => date('Y-m-d H:i:s', 1398966043),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'kiari',
				'email' => 'kiarigordon@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1995-08-09',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1398969570),
				'updated_at' => date('Y-m-d H:i:s', 1398969570),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Estevanrodri',
				'name' => 'Estevan Rodriguez',
				'email' => 'Estevanrodri512@GMail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1994-08-25',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1398969897),
				'updated_at' => date('Y-m-d H:i:s', 1398969897),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'novin',
				'email' => 'novinshafigh74@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1991-11-14',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1398978573),
				'updated_at' => date('Y-m-d H:i:s', 1398978573),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Steve',
				'name' => 'Stephen Young',
				'email' => 'sdyoungii@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1984-02-14',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1399094079),
				'updated_at' => date('Y-m-d H:i:s', 1399094079),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'john',
				'email' => 'fuckme@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1991-11-12',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1399314604),
				'updated_at' => date('Y-m-d H:i:s', 1399314604),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Elizabeth Navarrete',
				'email' => 'eli.nav@live.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1984-10-05',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1399321539),
				'updated_at' => date('Y-m-d H:i:s', 1399321539),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Susana',
				'email' => 'sbgb93@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1993-08-11',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1399330725),
				'updated_at' => date('Y-m-d H:i:s', 1399330725),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Joshua Drayer',
				'email' => 'oakleydrayer1@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1993-02-14',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1399863592),
				'updated_at' => date('Y-m-d H:i:s', 1399863592),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'WadeSBROWN',
				'name' => 'Wade Brown',
				'email' => 'wadesbrown@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1982-11-02',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1401231313),
				'updated_at' => date('Y-m-d H:i:s', 1401231313),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Reza',
				'email' => 'rezy55@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1994-02-05',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1401920470),
				'updated_at' => date('Y-m-d H:i:s', 1401920470),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'wes',
				'name' => 'Weston Lippia',
				'email' => 'wlippia@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1987-05-29',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1401988584),
				'updated_at' => date('Y-m-d H:i:s', 1401988584),
				'available' => 1,
				'bio' => 'MA - Public Policy, University of Nevada, Reno
			BA - Political Science, University of Nevada, Reno

			Received my graduate degree in public policy, with a heavy dose of writing and statistical analysis thrown in for good measure.  I am a friendly and supportive instructor who wants to see the best of those learning with me.   I have been published as a journalist by Yahoo! Sports, sold advertising, and guest lectured in graduate-level seminars.',
				'price' => '35.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Reza',
				'email' => 'rezam525@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1991-07-12',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1403039550),
				'updated_at' => date('Y-m-d H:i:s', 1403039550),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Erin Carleton',
				'email' => 'carletek@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1989-01-07',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1405892938),
				'updated_at' => date('Y-m-d H:i:s', 1405892938),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Joit',
				'name' => 'Tony',
				'email' => 'bart-69@mail.ru',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1994-10-14',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1406016499),
				'updated_at' => date('Y-m-d H:i:s', 1406016499),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'm0',
				'name' => 'mo',
				'email' => 'reza555@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1987-04-04',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1406321848),
				'updated_at' => date('Y-m-d H:i:s', 1406321848),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'cristu97',
				'name' => 'Neacsu',
				'email' => 'cristyan120@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1997-06-16',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1406974918),
				'updated_at' => date('Y-m-d H:i:s', 1406974918),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'upendra singh',
				'email' => 'upendrasingh370@gmail.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1992-03-10',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1407046086),
				'updated_at' => date('Y-m-d H:i:s', 1407046086),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => '',
				'name' => 'Josh',
				'email' => 'josah@yahoo.com',
				'password' => Hash::make(str_random(16)),
				'birthday' => '2002-03-02',
				'gender' => 'female',
				'created_at' => date('Y-m-d H:i:s', 1407129305),
				'updated_at' => date('Y-m-d H:i:s', 1407129305),
				'available' => 0,
				'bio' => '',
				'price' => '20.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			),
			array(
				'nickname' => 'Ed',
				'name' => 'Edward Engel',
				'email' => 'edengel@earthlink.net',
				'password' => Hash::make(str_random(16)),
				'birthday' => '1964-01-15',
				'gender' => 'male',
				'created_at' => date('Y-m-d H:i:s', 1408375832),
				'updated_at' => date('Y-m-d H:i:s', 1408375832),
				'available' => 0,
				'bio' => 'I have a BFA from OTIS Art Institute/Parsons School of Design(they were combined at the time) in Communication Design & Illustration. Just received my MFA in Media Design from Full Sail University. 

			My first job interview after getting my BFA I was offered a job at Bass Yager & Assoc(yes Saul Bass), but I couldn\'t take the job for financial reasons. My second job interview was with Walt Disney Imagineering. I spent the next few years(along with other OTIS grads) working as an Imagineer on all the Disney Parks. Later, I continued working on theme parks. After a couple years of that, I went to work for Mattel Toys. I learned a lot about the toy industry. 

			Not long after that I moved back to the midwest for family reasons and worked for some of the bigger advertising agencies here in Saint Louis. Got very lucky and worked on some major clients. Started my own business in 2001 and for the past 7 years I have been teaching at a couple local colleges. I have a lot of experiences to share.

			My email is edengel@earthlink.net Website http://edengel1.wix.com/edwardengel13#!work/cjg9',
				'price' => '50.00',
				'profile_picture' => '',
				'remember_token' => str_random(60)
			)
		);

		// Run the seeder
		$c = count($users);
		foreach ($users as $i => $user)
		{
			echo $i+1 . " / " . $c . " records inserted\r";
			DB::table('users')->insert($user);
		}
		echo "\nDone\r\n";
	}

}
