<?php

class SubjectsTableSeeder extends Seeder {

	public function run()
	{
		DB::disableQueryLog();

		$subjects = array(
		  array('main_subject_id' => '1', 'name' => 'Algebra'),
		  array('main_subject_id' => '1', 'name' => 'Calculus'),
		  array('main_subject_id' => '1', 'name' => 'Statistics'),
		  array('main_subject_id' => '1', 'name' => 'Geometry'),
		  array('main_subject_id' => '1', 'name' => 'Algebra 2'),
		  array('main_subject_id' => '1', 'name' => 'Trigonemtry'),
		  array('main_subject_id' => '1', 'name' => 'Algebra 1'),
		  array('main_subject_id' => '1', 'name' => 'Applied Math'),
		  array('main_subject_id' => '1', 'name' => 'Pre Algebra'),
		  array('main_subject_id' => '1', 'name' => 'Pre Calculus'),
		  array('main_subject_id' => '1', 'name' => 'Differential Equations'),
		  array('main_subject_id' => '1', 'name' => 'Arithmetic'),
		  array('main_subject_id' => '1', 'name' => 'Problem solving'),
		  array('main_subject_id' => '1', 'name' => 'Equations'),
		  array('main_subject_id' => '2', 'name' => 'English'),
		  array('main_subject_id' => '2', 'name' => 'Reading'),
		  array('main_subject_id' => '2', 'name' => 'Writing'),
		  array('main_subject_id' => '2', 'name' => 'Spelling'),
		  array('main_subject_id' => '2', 'name' => 'Grammar'),
		  array('main_subject_id' => '2', 'name' => 'Essay'),
		  array('main_subject_id' => '2', 'name' => 'Speech'),
		  array('main_subject_id' => '2', 'name' => 'Reading (dyslexia)'),
		  array('main_subject_id' => '2', 'name' => 'Vocabulary'),
		  array('main_subject_id' => '2', 'name' => 'Creative Writing'),
		  array('main_subject_id' => '2', 'name' => 'Literature'),
		  array('main_subject_id' => '2', 'name' => 'Term Paper'),
		  array('main_subject_id' => '2', 'name' => 'Punctuation'),
		  array('main_subject_id' => '2', 'name' => 'Phonics'),
		  array('main_subject_id' => '3', 'name' => 'Chemistry'),
		  array('main_subject_id' => '3', 'name' => 'Physics'),
		  array('main_subject_id' => '3', 'name' => 'Science'),
		  array('main_subject_id' => '3', 'name' => 'Biology'),
		  array('main_subject_id' => '3', 'name' => 'Pharmacology'),
		  array('main_subject_id' => '3', 'name' => 'Physical Chemistry'),
		  array('main_subject_id' => '3', 'name' => 'Organic Chemistry'),
		  array('main_subject_id' => '3', 'name' => 'Biochemistry'),
		  array('main_subject_id' => '3', 'name' => 'Physiology'),
		  array('main_subject_id' => '3', 'name' => 'Anatomy'),
		  array('main_subject_id' => '3', 'name' => 'Genetics'),
		  array('main_subject_id' => '3', 'name' => 'Psychology'),
		  array('main_subject_id' => '3', 'name' => 'Astronomy'),
		  array('main_subject_id' => '3', 'name' => 'Neuroscience'),
		  array('main_subject_id' => '3', 'name' => 'Geology'),
		  array('main_subject_id' => '3', 'name' => 'Computational Neuroscience'),
		  array('main_subject_id' => '3', 'name' => 'Cognitive Psychology'),
		  array('main_subject_id' => '3', 'name' => 'Meteorology'),
		  array('main_subject_id' => '3', 'name' => 'Geography'),
		  array('main_subject_id' => '3', 'name' => 'Geophysics'),
		  array('main_subject_id' => '3', 'name' => 'Thermodynamics'),
		  array('main_subject_id' => '4', 'name' => 'Spanish'),
		  array('main_subject_id' => '4', 'name' => 'ESL'),
		  array('main_subject_id' => '4', 'name' => 'French'),
		  array('main_subject_id' => '4', 'name' => 'German'),
		  array('main_subject_id' => '4', 'name' => 'Arabic'),
		  array('main_subject_id' => '4', 'name' => 'Japanese'),
		  array('main_subject_id' => '4', 'name' => 'Chinese'),
		  array('main_subject_id' => '4', 'name' => 'Russian'),
		  array('main_subject_id' => '4', 'name' => 'Latin'),
		  array('main_subject_id' => '4', 'name' => 'Italian'),
		  array('main_subject_id' => '4', 'name' => 'Mandarin'),
		  array('main_subject_id' => '4', 'name' => 'Portuguese'),
		  array('main_subject_id' => '4', 'name' => 'Hindi'),
		  array('main_subject_id' => '4', 'name' => 'Hebrew'),
		  array('main_subject_id' => '4', 'name' => 'Cantonese'),
		  array('main_subject_id' => '4', 'name' => 'Creole'),
		  array('main_subject_id' => '4', 'name' => 'Dutch'),
		  array('main_subject_id' => '5', 'name' => 'GRE'),
		  array('main_subject_id' => '5', 'name' => 'ACT'),
		  array('main_subject_id' => '5', 'name' => 'GED'),
		  array('main_subject_id' => '5', 'name' => 'PRAXIS'),
		  array('main_subject_id' => '5', 'name' => 'GMAT'),
		  array('main_subject_id' => '5', 'name' => 'LSAT'),
		  array('main_subject_id' => '5', 'name' => 'ISEE'),
		  array('main_subject_id' => '5', 'name' => 'CLEP'),
		  array('main_subject_id' => '5', 'name' => 'MCAT'),
		  array('main_subject_id' => '5', 'name' => 'TOEFL'),
		  array('main_subject_id' => '5', 'name' => 'SSAT'),
		  array('main_subject_id' => '5', 'name' => 'DAT'),
		  array('main_subject_id' => '5', 'name' => 'SAT'),
		  array('main_subject_id' => '5', 'name' => 'USMLE'),
		  array('main_subject_id' => '6', 'name' => 'Accounting'),
		  array('main_subject_id' => '6', 'name' => 'CPA'),
		  array('main_subject_id' => '6', 'name' => 'Finance'),
		  array('main_subject_id' => '6', 'name' => 'Economics'),
		  array('main_subject_id' => '6', 'name' => 'Business Accounting'),
		  array('main_subject_id' => '6', 'name' => 'Managament Skills'),
		  array('main_subject_id' => '6', 'name' => 'Marketing'),
		  array('main_subject_id' => '6', 'name' => 'Start-up Business'),
		  array('main_subject_id' => '6', 'name' => 'Business Management'),
		  array('main_subject_id' => '6', 'name' => 'Business Plan'),
		  array('main_subject_id' => '6', 'name' => 'Real Estate'),
		  array('main_subject_id' => '6', 'name' => 'Project Management'),
		  array('main_subject_id' => '6', 'name' => 'Human Resources'),
		  array('main_subject_id' => '6', 'name' => 'Taxes'),
		  array('main_subject_id' => '7', 'name' => 'Computer'),
		  array('main_subject_id' => '7', 'name' => 'JAVA'),
		  array('main_subject_id' => '7', 'name' => 'Programming'),
		  array('main_subject_id' => '7', 'name' => 'C++'),
		  array('main_subject_id' => '7', 'name' => 'Photoshop'),
		  array('main_subject_id' => '7', 'name' => 'Computer Science'),
		  array('main_subject_id' => '7', 'name' => 'Computer Programming'),
		  array('main_subject_id' => '7', 'name' => 'HTML'),
		  array('main_subject_id' => '7', 'name' => 'SQL'),
		  array('main_subject_id' => '7', 'name' => 'Microsoft Excel'),
		  array('main_subject_id' => '7', 'name' => 'SAS'),
		  array('main_subject_id' => '7', 'name' => 'Python'),
		  array('main_subject_id' => '7', 'name' => 'Internet'),
		  array('main_subject_id' => '7', 'name' => 'Keyboard'),
		  array('main_subject_id' => '7', 'name' => 'Database'),
		  array('main_subject_id' => '7', 'name' => 'Javascript'),
		  array('main_subject_id' => '7', 'name' => 'C'),
		  array('main_subject_id' => '7', 'name' => 'Microsoft Access'),
		  array('main_subject_id' => '7', 'name' => 'Microsoft Word'),
		  array('main_subject_id' => '7', 'name' => 'Algorithms'),
		  array('main_subject_id' => '7', 'name' => 'Unix'),
		  array('main_subject_id' => '7', 'name' => 'Visual Basic'),
		  array('main_subject_id' => '7', 'name' => 'Linux'),
		  array('main_subject_id' => '7', 'name' => 'PHP'),
		  array('main_subject_id' => '7', 'name' => 'ASP.NET'),
		  array('main_subject_id' => '7', 'name' => 'VB.NET'),
		  array('main_subject_id' => '7', 'name' => 'MySQL'),
		  array('main_subject_id' => '7', 'name' => 'Word Processing'),
		  array('main_subject_id' => '7', 'name' => 'Combination Algorithms'),
		  array('main_subject_id' => '7', 'name' => 'Ruby on Rails'),
		  array('main_subject_id' => '7', 'name' => 'Microsoft FoxPro'),
		  array('main_subject_id' => '7', 'name' => 'Perl'),
		  array('main_subject_id' => '7', 'name' => 'C#'),
		  array('main_subject_id' => '7', 'name' => 'Adobe Illustrator'),
		  array('main_subject_id' => '7', 'name' => 'Computer Engineering'),
		  array('main_subject_id' => '8', 'name' => 'Piano'),
		  array('main_subject_id' => '8', 'name' => 'Guitar'),
		  array('main_subject_id' => '8', 'name' => 'Violin'),
		  array('main_subject_id' => '8', 'name' => 'Dance'),
		  array('main_subject_id' => '8', 'name' => 'Music'),
		  array('main_subject_id' => '8', 'name' => 'Flute'),
		  array('main_subject_id' => '8', 'name' => 'Lute'),
		  array('main_subject_id' => '8', 'name' => 'Composition'),
		  array('main_subject_id' => '8', 'name' => 'Saxophone'),
		  array('main_subject_id' => '8', 'name' => 'Trumpet'),
		  array('main_subject_id' => '8', 'name' => 'Tap Dance'),
		  array('main_subject_id' => '8', 'name' => 'Cello'),
		  array('main_subject_id' => '8', 'name' => 'Music Theory'),
		  array('main_subject_id' => '8', 'name' => 'Accordion'),
		  array('main_subject_id' => '9', 'name' => 'Karate'),
		  array('main_subject_id' => '9', 'name' => 'Basketball'),
		  array('main_subject_id' => '9', 'name' => 'Tennis'),
		  array('main_subject_id' => '9', 'name' => 'Surfing'),
		  array('main_subject_id' => '9', 'name' => 'Swimming'),
		  array('main_subject_id' => '9', 'name' => 'Ballet'),
		  array('main_subject_id' => '9', 'name' => 'Drums'),
		  array('main_subject_id' => '9', 'name' => 'Aerobics'),
		  array('main_subject_id' => '9', 'name' => 'Jeet Kune Do'),
		  array('main_subject_id' => '9', 'name' => 'Yoga'),
		  array('main_subject_id' => '9', 'name' => 'Volleyball'),
		  array('main_subject_id' => '9', 'name' => 'Triathlon'),
		  array('main_subject_id' => '9', 'name' => 'Gymnastics'),
		  array('main_subject_id' => '9', 'name' => 'Boxing'),
		  array('main_subject_id' => '10', 'name' => 'Elementary'),
		  array('main_subject_id' => '10', 'name' => 'History'),
		  array('main_subject_id' => '10', 'name' => 'Dyslexia'),
		  array('main_subject_id' => '10', 'name' => 'Education'),
		  array('main_subject_id' => '10', 'name' => 'Study Skills'),
		  array('main_subject_id' => '10', 'name' => 'Special Education'),
		  array('main_subject_id' => '10', 'name' => 'Sewing'),
		  array('main_subject_id' => '10', 'name' => 'Home Schooling'),
		  array('main_subject_id' => '10', 'name' => 'Philosophy'),
		  array('main_subject_id' => '10', 'name' => 'Social Studies'),
		  array('main_subject_id' => '10', 'name' => 'World History'),
		  array('main_subject_id' => '10', 'name' => 'Nursing'),
		  array('main_subject_id' => '10', 'name' => 'Civil Engineering'),
		  array('main_subject_id' => '10', 'name' => 'Sociology '),
		  array('main_subject_id' => '10', 'name' => 'Zoology'),
		  array('main_subject_id' => '10', 'name' => 'Nutrition'),
		  array('main_subject_id' => '10', 'name' => 'Chemical Engineering'),
		  array('main_subject_id' => '10', 'name' => 'Calligraphy '),
		  array('main_subject_id' => '10', 'name' => 'Biotechnology'),
		  array('main_subject_id' => '10', 'name' => 'Law'),
		  array('main_subject_id' => '10', 'name' => 'Government'),
		  array('main_subject_id' => '10', 'name' => 'Electrical Engineering'),
		  array('main_subject_id' => '10', 'name' => 'Communications'),
		  array('main_subject_id' => '10', 'name' => 'Sound'),
		  array('main_subject_id' => '10', 'name' => 'Driving'),
		  array('main_subject_id' => '10', 'name' => 'DMV exam'),
		  array('main_subject_id' => '10', 'name' => 'Acting'),
		  array('main_subject_id' => '10', 'name' => 'American history'),
		  array('main_subject_id' => '10', 'name' => 'Painting'),
		  array('main_subject_id' => '10', 'name' => 'Fine Arts'),
		  array('main_subject_id' => '10', 'name' => 'Industrial Engineering'),
		  array('main_subject_id' => '10', 'name' => 'Genetic Engineering'),
		  array('main_subject_id' => '10', 'name' => 'Logic'),
		  array('main_subject_id' => '10', 'name' => 'Knitting'),
		  array('main_subject_id' => '10', 'name' => 'Graphic Design'),
		  array('main_subject_id' => '10', 'name' => 'Journalism'),
		  array('main_subject_id' => '10', 'name' => 'Heat Transfer'),
		  array('main_subject_id' => '10', 'name' => 'European History'),
		  array('main_subject_id' => '10', 'name' => 'Sign Language'),
		  array('main_subject_id' => '10', 'name' => 'Coaching'),
		  array('main_subject_id' => '10', 'name' => 'Pottery'),
		  array('main_subject_id' => '10', 'name' => 'Political Science'),
		  array('main_subject_id' => '10', 'name' => 'Photography'),
		  array('main_subject_id' => '10', 'name' => 'Emergency Medicine'),
		  array('main_subject_id' => '4', 'name' => 'Gàidhlig'),
		  array('main_subject_id' => '6', 'name' => 'SEO'),
		  array('main_subject_id' => '6', 'name' => 'SMO'),
		  array('main_subject_id' => '6', 'name' => 'Online Marketing'),
		  array('main_subject_id' => '7', 'name' => 'CSS'),
		  array('main_subject_id' => '8', 'name' => 'Logic Pro'),
		  array('main_subject_id' => '8', 'name' => 'Sound Design'),
		  array('main_subject_id' => '10', 'name' => 'Sonography')
		);

		// Run the seeder
		$c = count($subjects);
		foreach ($subjects as $i => $subject)
		{
			echo $i+1 . " / " . $c . " records inserted\r";
			DB::table('subjects')->insert($subject);
		}
		echo "\nDone\r\n";
	}

}
